-- How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤
-- 100 and 2 ≤ b ≤ 100?
import qualified Data.List as List

-- Nice readable list comprehension
terms :: Integer -> [Integer]
terms n = [a ^ b | a <- [2..n], b <- [2..n]]

-- Equivalent incomprehensible functor magic
-- We lift (^) and sequentially apply the arguments using instance Applicative List
termsF :: Integer -> [Integer]
termsF n = (^) <$> [2..n] <*> [2..n]
-- ... which GHC compiles back down into a list comprehension!
-- https://hackage.haskell.org/package/base-4.18.0.0/docs/src/GHC.Base.html#line-1253

-- Get the number of unique terms in the sequence
solve :: Integer -> Int
solve = length . uniq . termsF
  where 
    uniq = List.map head . List.group . List.sort

main :: IO ()
main = putStrLn $ show $ solve 100

